# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: At the end of internet
# --- email: t a s h e p k o v atttt g m a i l dottt com
description: >
  When your problems seem like mountains,
  you can keep them for another day.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # http://trggr.github.io" # the base hostname & protocol for your site
github_username:  trggr

# Build settings
#markdown: kramdown
theme: minima
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
